export const feedbackList = [
  {
    value: 'ability_to_learn',
    label: 'Ability to learn/ Cognitive ability',
  },
  { value: 'analytical_skills', label: 'Analytical skills' },
  { value: 'attitude', label: 'Attitude' },
  { value: 'c', label: 'C' },
  { value: 'c++', label: 'C++' },
  { value: 'communication_skill', label: 'Communication Skill' },
  { value: 'content_marketing', label: 'Content Marketing' },
  { value: 'content_writing', label: 'Content Writing' },
  { value: 'cultural_fit_attitude', label: 'Cultural Fit/Attitude' },
  { value: 'interpersonal_skills', label: 'Interpersonal skills' },
  { value: 'java', label: 'Java' },
  { value: 'javascript', label: 'Javascript' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'paid_campaigns', label: 'Paid campaigns' },
  { value: 'payroll_understanding', label: 'Payroll Understanding' },
  { value: 'python', label: 'Python' },
  { value: 'react', label: 'React' },
  { value: 'recruitment', label: 'Recruitment' },
  { value: 'sales', label: 'Sales' },
  { value: 'sales_approach', label: 'Sales approach' },
  { value: 'sales_pitch', label: 'Sales pitch' },
  { value: 'social_media_marketing', label: 'Social media marketing' },
  { value: 'sql', label: 'SQL' },
  { value: 'taxation', label: 'Taxation' },
  { value: 'tech_recruitment', label: 'Tech Recruitment' },
  { value: 'technical_skills', label: 'Technical skills' },
  { value: 'wordpress', label: 'Wordpress' },
]
