export const feedbackList = [
  'Ability to learn/ Cognitive ability',
  'Analytical skills',
  'Attitude',
  'C',
  'C++',
  'Communication Skill',
  'Content Marketing',
  'Content Writing',
  'Cultural Fit/Attitude',
  'Interpersonal skills',
  'Java',
  'Javascript',
  'Marketing',
  'Paid campaigns',
  'Payroll Understanding',
  'Python',
  'React',
  'Recruitment',
  'Sales',
  'Sales approach',
  'Sales pitch',
  'Social media marketing',
  'SQL',
  'Taxation',
  'Tech Recruitment',
  'Technical skills',
  'Wordpress',
]
