export const jobTypeOptions = [
  { value: 'fullTime', label: 'Full Time' },
  { value: 'partTime', label: 'Part Time' },
  { value: 'contract', label: 'Contract' },
  { value: 'internship', label: 'Internship' },
]

export const experienceOptions = [
  { label: '< 3 years', value: '< 3 years' },
  { label: '3-5 years', value: '3-5 years' },
  { label: '5-7 years', value: '5-7 years' },
  { label: '7-10 years', value: '7-10 years' },
  { label: '> 10 years', value: '> 10 years' },
]

export const skillList = [
  { key: 1, value: 'HTML' },
  { key: 2, value: 'CSS' },
  { key: 3, value: 'JavaScript' },
  { key: 4, value: 'React' },
  { key: 5, value: 'Node' },
  { key: 6, value: 'Python' },
  { key: 7, value: 'Java' },
  { key: 8, value: 'C++' },
  { key: 9, value: 'C#' },
  { key: 10, value: 'C' },
  { key: 11, value: 'Ruby' },
  { key: 12, value: 'PHP' },
  { key: 13, value: 'Go' },
  { key: 14, value: 'Swift' },
  { key: 15, value: 'Kotlin' },
  { key: 16, value: 'Rust' },
  { key: 17, value: 'Dart' },
  { key: 18, value: 'SQL' },
  { key: 19, value: 'NoSQL' },
  { key: 20, value: 'MongoDB' },
  { key: 21, value: 'MySQL' },
  { key: 22, value: 'PostgreSQL' },
  { key: 23, value: 'Firebase' },
  { key: 24, value: 'AWS' },
  { key: 25, value: 'GCP' },
  { key: 26, value: 'Azure' },
  { key: 27, value: 'Docker' },
  { key: 28, value: 'Kubernetes' },
  { key: 29, value: 'Git' },
  { key: 30, value: 'GitHub' },
  { key: 31, value: 'GitLab' },
  { key: 32, value: 'BitBucket' },
  { key: 33, value: 'Jira' },
  { key: 34, value: 'Confluence' },
  { key: 35, value: 'Trello' },
  { key: 36, value: 'Slack' },
  { key: 41, value: 'Figma' },
  { key: 42, value: 'Adobe XD' },
  { key: 43, value: 'Sketch' },
  { key: 44, value: 'Invision' },
  { key: 45, value: 'Zeplin' },
  { key: 46, value: 'Adobe Photoshop' },
  { key: 47, value: 'Adobe Illustrator' },
  { key: 48, value: 'Adobe Premiere Pro' },
  { key: 49, value: 'Adobe After Effects' },
  { key: 50, value: 'Adobe Lightroom' },
  { key: 51, value: 'Adobe Audition' },
  { key: 52, value: 'Adobe InDesign' },
  { key: 53, value: 'Communication' },
  { key: 54, value: 'Teamwork' },
  { key: 55, value: 'Leadership' },
  { key: 56, value: 'Problem Solving' },
  { key: 57, value: 'Creativity' },
  { key: 58, value: 'Critical Thinking' },
  { key: 59, value: 'Time Management' },
  { key: 60, value: 'Organization' },
  { key: 61, value: 'Adaptability' },
  { key: 62, value: 'Flexibility' },
  { key: 63, value: 'Attention to Detail' },
  { key: 64, value: 'Accounting' },
  { key: 65, value: 'Finance' },
  { key: 66, value: 'Economics' },
  { key: 67, value: 'Business' },
  { key: 68, value: 'Marketing' },
  { key: 69, value: 'Sales' },
  { key: 70, value: 'Public Relations' },
  { key: 71, value: 'Human Resources' },
  { key: 72, value: 'Research' },
]

export const currency_list = [
  { label: 'Indian Rupee (₹)', value: 'inr' },
  { label: 'US Dollar ($)', value: 'usd' },
]
// export const currency_list = [
//   { key: 1, value: 'Afghan Afghani (؋)' },
//   { key: 2, value: 'Albanian Lek (Lek)' },
//   { key: 3, value: 'Algerian Dinar (دج)' },
//   { key: 4, value: 'Angolan Kwanza (Kz)' },
//   { key: 5, value: 'Argentine Peso ($)' },
//   { key: 6, value: 'Armenian Dram (֏)' },
//   { key: 7, value: 'Aruban Florin (ƒ)' },
//   { key: 8, value: 'Australian Dollar ($)' },
//   { key: 9, value: 'Azerbaijani Manat (m)' },
//   { key: 10, value: 'Bahamian Dollar (B$)' },
//   { key: 11, value: 'Bahraini Dinar (.د.ب)' },
//   { key: 12, value: 'Bangladeshi Taka (৳)' },
//   { key: 13, value: 'Barbadian Dollar (Bds$)' },
//   { key: 14, value: 'Belarusian Ruble (Br)' },
//   { key: 15, value: 'Belgian Franc (fr)' },
//   { key: 16, value: 'Belize Dollar ($)' },
//   { key: 17, value: 'Bermudan Dollar ($)' },
//   { key: 18, value: 'Bhutanese Ngultrum (Nu.)' },
//   { key: 19, value: 'Bitcoin (฿)' },
//   { key: 20, value: 'Bolivian Boliviano (Bs.)' },
//   { key: 21, value: 'Bosnia-Herzegovina Convertible Mark (KM)' },
//   { key: 22, value: 'Botswanan Pula (P)' },
//   { key: 23, value: 'Brazilian Real (R$)' },
//   { key: 24, value: 'British Pound Sterling (£)' },
//   { key: 25, value: 'Brunei Dollar (B$)' },
//   { key: 26, value: 'Bulgarian Lev (Лв.)' },
//   { key: 27, value: 'Burundian Franc (FBu)' },
//   { key: 28, value: 'Cambodian Riel (KHR)' },
//   { key: 29, value: 'Canadian Dollar ($)' },
//   { key: 30, value: 'Cape Verdean Escudo ($)' },
//   { key: 31, value: 'Cayman Islands Dollar ($)' },
//   { key: 32, value: 'CFA Franc BCEAO (CFA)' },
//   { key: 33, value: 'CFA Franc BEAC (FCFA)' },
//   { key: 34, value: 'CFP Franc (₣)' },
//   { key: 35, value: 'Chilean Peso ($)' },
//   { key: 36, value: 'Chinese Yuan (¥)' },
//   { key: 37, value: 'Colombian Peso ($)' },
//   { key: 38, value: 'Comorian Franc (CF)' },
//   { key: 39, value: 'Congolese Franc (FC)' },
//   { key: 40, value: 'Costa Rican ColÃ³n (₡)' },
//   { key: 41, value: 'Croatian Kuna (kn)' },
//   { key: 42, value: 'Cuban Convertible Peso ($, CUC)' },
//   { key: 43, value: 'Czech Republic Koruna (Kč)' },
//   { key: 44, value: 'Danish Krone (Kr.)' },
//   { key: 45, value: 'Djiboutian Franc (Fdj)' },
//   { key: 46, value: 'Dominican Peso ($)' },
//   { key: 47, value: 'East Caribbean Dollar ($)' },
//   { key: 48, value: 'Egyptian Pound (ج.م)' },
//   { key: 49, value: 'Eritrean Nakfa (Nfk)' },
//   { key: 50, value: 'Estonian Kroon (kr)' },
//   { key: 51, value: 'Ethiopian Birr (Nkf)' },
//   { key: 52, value: 'Euro (€)' },
//   { key: 53, value: 'Falkland Islands Pound (£)' },
//   { key: 54, value: 'Fijian Dollar (FJ$)' },
//   { key: 55, value: 'Gambian Dalasi (D)' },
//   { key: 56, value: 'Georgian Lari (ლ)' },
//   { key: 57, value: 'German Mark (DM)' },
//   { key: 58, value: 'Ghanaian Cedi (GH₵)' },
//   { key: 59, value: 'Gibraltar Pound (£)' },
//   { key: 60, value: 'Greek Drachma (₯, Δρχ, Δρ)' },
//   { key: 61, value: 'Guatemalan Quetzal (Q)' },
//   { key: 62, value: 'Guinean Franc (FG)' },
//   { key: 63, value: 'Guyanaese Dollar ($)' },
//   { key: 64, value: 'Haitian Gourde (G)' },
//   { key: 65, value: 'Honduran Lempira (L)' },
//   { key: 66, value: 'Hong Kong Dollar ($)' },
//   { key: 67, value: 'Hungarian Forint (Ft)' },
//   { key: 68, value: 'Icelandic KrÃ³na (kr)' },
//   { key: 69, value: 'Indian Rupee (₹)' },
//   { key: 70, value: 'Indonesian Rupiah (Rp)' },
//   { key: 71, value: 'Iranian Rial (﷼)' },
//   { key: 72, value: 'Iraqi Dinar (د.ع)' },
//   { key: 73, value: 'Israeli New Sheqel (₪)' },
//   { key: 74, value: 'Italian Lira (L,£)' },
//   { key: 75, value: 'Jamaican Dollar (J$)' },
//   { key: 76, value: 'Japanese Yen (¥)' },
//   { key: 77, value: 'Jordanian Dinar (ا.د)' },
//   { key: 78, value: 'Kazakhstani Tenge (лв)' },
//   { key: 79, value: 'Kenyan Shilling (KSh)' },
//   { key: 80, value: 'Kuwaiti Dinar (ك.د)' },
//   { key: 81, value: 'Kyrgystani Som (лв)' },
//   { key: 82, value: 'Laotian Kip (₭)' },
//   { key: 83, value: 'Latvian Lats (Ls)' },
//   { key: 84, value: 'Lebanese Pound (£)' },
//   { key: 85, value: 'Lesotho Loti (L)' },
//   { key: 86, value: 'Liberian Dollar ($)' },
//   { key: 87, value: 'Libyan Dinar (د.ل)' },
//   { key: 88, value: 'Lithuanian Litas (Lt)' },
//   { key: 89, value: 'Macanese Pataca ($)' },
//   { key: 90, value: 'Macedonian Denar (ден)' },
//   { key: 91, value: 'Malagasy Ariary (Ar)' },
//   { key: 92, value: 'Malawian Kwacha (MK)' },
//   { key: 93, value: 'Malaysian Ringgit (RM)' },
//   { key: 94, value: 'Maldivian Rufiyaa (Rf)' },
//   { key: 95, value: 'Mauritanian Ouguiya (MRU)' },
//   { key: 96, value: 'Mauritian Rupee (₨)' },
//   { key: 97, value: 'Mexican Peso ($)' },
//   { key: 98, value: 'Moldovan Leu (L)' },
//   { key: 99, value: 'Mongolian Tugrik (₮)' },
//   { key: 100, value: 'Moroccan Dirham (MAD)' },
//   { key: 101, value: 'Mozambican Metical (MT)' },
//   { key: 102, value: 'Myanmar Kyat (K)' },
//   { key: 103, value: 'Namibian Dollar ($)' },
//   { key: 104, value: 'Nepalese Rupee (₨)' },
//   { key: 105, value: 'Netherlands Antillean Guilder (ƒ)' },
//   { key: 106, value: 'New Taiwan Dollar ($)' },
//   { key: 107, value: 'New Zealand Dollar ($)' },
//   { key: 108, value: 'Nicaraguan CÃ³rdoba (C$)' },
//   { key: 109, value: 'Nigerian Naira (₦)' },
//   { key: 110, value: 'North Korean Won (₩)' },
//   { key: 111, value: 'Norwegian Krone (kr)' },
//   { key: 112, value: 'Omani Rial (.ع.ر)' },
//   { key: 113, value: 'Pakistani Rupee (₨)' },
//   { key: 114, value: 'Panamanian Balboa (B/.)' },
//   { key: 115, value: 'Papua New Guinean Kina (K)' },
//   { key: 116, value: 'Paraguayan Guarani (₲)' },
//   { key: 117, value: 'Peruvian Nuevo Sol (S/.)' },
//   { key: 118, value: 'Philippine Peso (₱)' },
//   { key: 119, value: 'Polish Zloty (zł)' },
//   { key: 120, value: 'Qatari Rial (ق.ر)' },
//   { key: 121, value: 'Romanian Leu (lei)' },
//   { key: 122, value: 'Russian Ruble (₽)' },
//   { key: 123, value: 'Rwandan Franc (FRw)' },
//   { key: 124, value: 'Salvadoran ColÃ³n (₡)' },
//   { key: 125, value: 'Samoan Tala (SAT)' },
//   { key: 126, value: 'Saudi Riyal (﷼)' },
//   { key: 127, value: 'Serbian Dinar (din)' },
//   { key: 128, value: 'Seychellois Rupee (SRe)' },
//   { key: 129, value: 'Sierra Leonean Leone (Le)' },
//   { key: 130, value: 'Singapore Dollar ($)' },
//   { key: 131, value: 'Slovak Koruna (Sk)' },
//   { key: 132, value: 'Solomon Islands Dollar (Si$)' },
//   { key: 133, value: 'Somali Shilling (Sh.so.)' },
//   { key: 134, value: 'South African Rand (R)' },
//   { key: 135, value: 'South Korean Won (₩)' },
//   { key: 136, value: 'Special Drawing Rights (SDR)' },
//   { key: 137, value: 'Sri Lankan Rupee (Rs)' },
//   { key: 138, value: 'St. Helena Pound (£)' },
//   { key: 139, value: 'Sudanese Pound (.س.ج)' },
//   { key: 140, value: 'Surinamese Dollar ($)' },
//   { key: 141, value: 'Swazi Lilangeni (E)' },
//   { key: 142, value: 'Swedish Krona (kr)' },
//   { key: 143, value: 'Swiss Franc (CHf)' },
//   { key: 144, value: 'Syrian Pound (LS)' },
//   { key: 145, value: 'São Tomé and Príncipe Dobra (Db)' },
//   { key: 146, value: 'Tajikistani Somoni (SM)' },
//   { key: 147, value: 'Tanzanian Shilling (TSh)' },
//   { key: 148, value: 'Thai Baht (฿)' },
//   { key: 149, value: "Tongan Pa'anga", symbol: '$)' },
//   { key: 150, value: 'Trinidad & Tobago Dollar ($)' },
//   { key: 151, value: 'Tunisian Dinar (ت.د)' },
//   { key: 152, value: 'Turkish Lira (₺)' },
//   { key: 153, value: 'Turkmenistani Manat (T)' },
//   { key: 154, value: 'Ugandan Shilling (USh)' },
//   { key: 155, value: 'Ukrainian Hryvnia (₴)' },
//   { key: 156, value: 'United Arab Emirates Dirham (إ.د)' },
//   { key: 157, value: 'Uruguayan Peso ($)' },
//   { key: 158, value: 'US Dollar ($)' },
//   { key: 159, value: 'Uzbekistan Som (лв)' },
//   { key: 160, value: 'Vanuatu Vatu (VT)' },
//   { key: 161, value: 'Venezuelan BolÃvar (Bs)' },
//   { key: 162, value: 'Vietnamese Dong (₫)' },
//   { key: 163, value: 'Yemeni Rial (﷼)' },
//   { key: 164, value: 'Zambian Kwacha (ZK)' },
// ]
